Feature/allow adding EDMM types
eclipse/winery pull request #694
Opened 2022-11-10 15:36 UTC by ghareeb-falazi

EDMM specifications allow the creation of component and relation types. However, Winery, which is supposed to support EDMM modeling, does not support adding new EDMM types.

This pull request allows adding EDMM types in Winery, which can be mapped to TOSCA types so that exporting in EDMM functions as expected.
Furthermore, TOSCA types will become the single source of truth, i.e., inheritance relations between TOSCA types are reflected in the exported EDMM file whatever they are.
Finally, only 1-to-1 mappings between TOSCA and EDMM types will remain. If a TOSCA type is not mapped to an EDMM type, a  new EDMM type is automatically created with a suitable name and the inheritance relationship is taken from the TOSCA type.

- [ ] Ensure that you followed our [toolchain guide](https://github.com/eclipse/winery/blob/main/docs/dev/github-workflow.md#github---prepare-final-pull-request). Especially, we require **a single commit**
- [ ] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Ensure to use auto format in **all** files
- [ ] Ensure that you appear in `NOTICE` at Copyright Holders
- [ ] Tests created for changes
- [ ] Documentation updated (if needed)
- [ ] Screenshots added (for UI changes)

2022-11-10 15:37 UTC, ghareeb-falazi commented
still wip

2022-11-17 14:09 UTC, lharzenetter requested changes

2022-12-20 14:10 UTC, ghareeb-falazi commented on org.eclipse.winery.edmm/src/main/java/org/eclipse/winery/edmm/JsonBasedEdmmManager.java
> +
done

2023-01-12 07:14 UTC, lharzenetter approved these changes

2023-01-12 07:15 UTC, merged